version: "3"

services:
  postgres:
    image: postgres:14.13-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: elestio/pgadmin:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    restart: always
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres:
  pgadmin:
  data: